# Generated by Django 2.2 on 2019-04-10 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=40)),
                ('venue', models.CharField(max_length=35)),
                ('time', models.TimeField()),
                ('fee', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('cover', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showcase.Event')),
            ],
        ),
    ]
